### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/release#133]
Tracker for all issues that should be solved before the next release. Please add anything you want to have considered in a comment below.

* [ ] gtk-rs/glib#637
* [ ] gtk-rs/glib#640
* [ ] https://github.com/gtk-rs/glib/issues/664
* [ ] https://github.com/gtk-rs/gio/issues/293
* [ ] gtk-rs/gtk#938
* [ ] gtk-rs/gtk#998
* [ ] gtk-rs/sourceview#130
* [ ] gtk-rs/gir#474 @GuillaumeGomez
* [ ] https://github.com/gtk-rs/gir/issues/746
* [ ] #114
* [ ] #113
* [ ] #117

**Comment by sdroege** [comment]
Closing in favour of https://github.com/gtk-rs/release/issues/137
