### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/release#94]
* [ ] https://github.com/gtk-rs/glib/issues/514 @sdroege 
* [x] Ending https://github.com/gtk-rs/gir/pull/816 @GuillaumeGomez 
  * [x] code regen
* [x] https://github.com/gtk-rs/gir/pull/826 @EPashkin 
  * [x] code regen
* [x] End to update cargo files to handle docs.rs better @GuillaumeGomez (https://github.com/gtk-rs/gir/pull/820)
* [x] gtk-rs/gir#825 @fengalin
* [x] gtk-rs/glib#513 @fengalin
* [x] gtk-rs/gio#233 @fengalin
* [x] gtk-rs/atk#36 @fengalin
* [x] gtk-rs/gdk-pixbuf#128 @fengalin
* [x] gtk-rs/gdk#307 @fengalin
* [x] gtk-rs/gtk#870 @fengalin
* [x] gtk-rs/examples#257 @fengalin
* [x] gtk-rs/gtk#871 @brainblasted
* [x] gtk-rs/gtk#873 @brainblasted
* [ ] https://github.com/gtk-rs/gtk/issues/874 @brainblasted @Cogitri
* [x] https://github.com/gtk-rs/gdk/issues/308
* [x] gtk-rs/gio#226 @cogitri
* [x] gtk-rs/gio#234 @federicomenaquintero
* [x] gtk-rs/gtk#878 @brainblasted
* [x] gtk-rs/gtk#879 @brainblasted
* [x] gtk-rs/gtk#880 @brainblasted
* [x] create a new crate to put utils macros into (and write the one for downgrade/upgrade!)
* [x] https://github.com/gtk-rs/gtk/issues/887 @GuillaumeGomez 
* [x] https://github.com/gtk-rs/gtk/issues/890 @GuillaumeGomez
* [x] https://github.com/gtk-rs/gir/issues/841 @GuillaumeGomez
* [x] https://github.com/gtk-rs/gir/issues/844 @GuillaumeGomez 
* [x] https://github.com/gtk-rs/gir/issues/845 @GuillaumeGomez 
* [ ] Regen all repositories so they all have the same gir version before release
* [x] gtk-rs/gdk#311 @bilelmoussaoui
* [x] https://github.com/gtk-rs/sys/issues/151
* [x] https://github.com/gtk-rs/sys/issues/135
* [x] https://github.com/gtk-rs/cairo/issues/285
* [x] Remove `glib` re-exports from all the other crates (see https://github.com/gtk-rs/gir/issues/862#issuecomment-545795246)
* [x] https://github.com/gtk-rs/gtk/pull/915 https://github.com/gtk-rs/gtk/issues/913 @sdroege 
* [x] https://github.com/gtk-rs/gio/issues/257 @sdroege 
* [x] https://github.com/gtk-rs/glib/issues/537 @sdroege 
* [x] https://github.com/gtk-rs/gtk/issues/914 @GuillaumeGomez 
* [x] https://github.com/gtk-rs/examples/pull/256 @alatiera
* [x] https://github.com/gtk-rs/gtk/issues/916 @alatiera
* [x] https://github.com/gtk-rs/glib/issues/543
* [x] https://github.com/gtk-rs/glib/issues/545 @sdroege 

If any other issues/PRs should be solved for this release please add them below as comment.

**Comment by sdroege** [comment]
CC @GuillaumeGomez @EPashkin @fengalin @brainblasted

**Comment by fengalin** [comment]
This is a tracking list for **"Code regen for gtk-rs/glib#513"**:

- [x] https://github.com/gtk-rs/gir/pull/825
- [x] https://github.com/gtk-rs/glib/pull/513
- [x] https://github.com/gtk-rs/gio/pull/233
- [ ] https://github.com/gtk-rs/atk/pull/36. CI failure expected (OK for crate). **Pending merge**.
- [ ] https://github.com/gtk-rs/gdk-pixbuf/pull/128. CI failure expected (OK for crate). **Pending merge**.
- [ ] https://github.com/fengalin/gdk/tree/value_get_result. PR creation pending https://github.com/gtk-rs/gdk-pixbuf/pull/128 merge.
- [ ] https://github.com/fengalin/gtk/tree/value_get_result. PR creation pending https://github.com/gtk-rs/atk/pull/36 merge & https://github.com/fengalin/gdk/tree/value_get_result merge (no PR yet).
- [ ] https://github.com/gtk-rs/examples/pull/257. CI OK using branches. Pending https://github.com/fengalin/gtk/tree/value_get_result (no PR yet).

Not part of `gtk-rs` organisation:

- [ ] [gstreamer-rs](https://gitlab.freedesktop.org/fengalin/gstreamer-rs/tree/value_get_result). CI OK using branches. Pending https://github.com/fengalin/gtk/tree/value_get_result (no PR yet).

**Comment by EPashkin** [comment]
@sdroege Please replace my https://github.com/gtk-rs/gir/pull/826 with https://github.com/gtk-rs/gir/issues/807

**Comment by BrainBlasted** [comment]
* [ ] https://github.com/gtk-rs/gtk/pull/871
* [ ] https://github.com/gtk-rs/gtk/pull/873

**Comment by Cogitri** [comment]
- [ ] https://github.com/gtk-rs/gio/pull/226

**Comment by federicomenaquintero** [comment]
* [ ] https://github.com/gtk-rs/gio/issues/234

**Comment by BrainBlasted** [comment]
* [ ] gtk-rs/gtk#878
* [ ] gtk-rs/gtk#879
* [ ] gtk-rs/gtk#880

**Comment by EPashkin** [comment]
code regen for gtk-rs/gir#826 is done

**Comment by bilelmoussaoui** [comment]
- [ ] https://github.com/gtk-rs/gdk/pull/311

**Comment by sdroege** [comment]
Let's target shortly after RustFest for the next release. Whatever is not finished at that point can also wait until the release afterwards :)

**Comment by sdroege** [comment]
At this point I would block on these 3 issues: gtk-rs/examples#256 gtk-rs/gtk#916 gtk-rs/glib#543

Let's get those fixed and then do a release next weekend? No further new features or anything, just bugfixes until then.

All other issues in the list above I would defer to next release. Doesn't look like people are actively working on them so it will have to wait.

**Comment by sdroege** [comment]
Still no release: remaining blockers are gtk-rs/cairo#293 and gtk-rs/gtk#916. I wouldn't consider https://github.com/gtk-rs/pango/pull/168 a blocker as a) it is just a new feature, new API, and b) nobody actually seems to be working on it so who knows when it will be finished.

CC @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I agree, I'll certainly finish the pango one myself to go faster.

**Comment by bilelmoussaoui** [comment]
I will finish the cairo merge request this weekend

**Comment by sdroege** [comment]
I think we're ready for release apart from some testing that will have to happen :)

>  Regen all repositories so they all have the same gir version before release

@GuillaumeGomez please don't forget this one when doing releases :)

**Comment by sdroege** [comment]
> @GuillaumeGomez please don't forget this one when doing releases :)

Also keep in mind that the -sys crates only need a bugfix release, not a new major release.

**Comment by EPashkin** [comment]
Seems release script now works fine.
Was only one problem with gtk-sys version, but it was not script error.
👍

**Comment by GuillaumeGomez** [comment]
I still had to make some last minute fixes but that's part of the game. ;)

**Comment by sdroege** [comment]
Release happened
